spring.application.name=social-login-project

# [1] ??? JDBC ???? ?? (?? DB ????? ???? ??? MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# [2] DB ?? URL ??
# ?? MySQL? sociallogin_db ??
# ?? ??? UTC? ??
# SSL ?? ???? (?? ?? ????? ??)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sociallogin_db?serverTimezone=UTC&useSSL=false

# [3] ?????? ?? ??? ??
spring.datasource.username=jeongsuhyeon

# [4] ?????? ?? ????
spring.datasource.password=0625

# [5] JPA ??
spring.jpa.hibernate.ddl-auto=update
#none : ?? ?? ? ?
#create : ?? ??? ?? ?? (?? ??? ???)
#creat-drop : ?? ? ?? ? ??? ??
#update : ??? ?? ??/?? (?? ??? ??)
#validate : ??? ?? ???, ?? x

# [6] ???? SQL ??? ??? ?? (??? ?)
spring.jpa.show-sql=true